<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOFmL9Zt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOFmL9Zt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOFmL9Zt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOFmL9Zt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOFmL9Zt\App_KernelDevDebugContainer([
    'container.build_hash' => 'OFmL9Zt',
    'container.build_id' => '4ebd9fe1',
    'container.build_time' => 1668089766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOFmL9Zt');
